# Generated by Django 3.2.8 on 2021-10-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=13)),
                ('unit', models.CharField(max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv.building')),
            ],
        ),
        migrations.CreateModel(
            name='HalfhourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=5, max_digits=9)),
                ('reading_date_time', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv.meterdata')),
            ],
        ),
    ]
