# Generated by Django 3.2.8 on 2021-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='fuel',
            field=models.CharField(choices=[('Water', 'Water'), ('Nautral Gas', 'Natural Gas'), ('Electricity', 'Electricity')], max_length=13),
        ),
    ]
