# Generated by Django 3.2.8 on 2021-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_alter_meterdata_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='building_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='fuel',
            field=models.CharField(max_length=13),
        ),
    ]
