# Generated by Django 3.2.8 on 2021-10-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0003_auto_20211010_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upload_csv.building'),
        ),
    ]
