# Generated by Django 3.2.8 on 2021-10-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0004_alter_meterdata_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfhourlydata',
            name='meter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv.meterdata'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='unit',
            field=models.CharField(max_length=4),
        ),
    ]
