# Generated by Django 3.2.8 on 2021-10-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0005_auto_20211010_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdata',
            name='meter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv.building'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
