# Generated by Django 3.2.8 on 2021-10-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0006_auto_20211010_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfhourlydata',
            name='meter_id',
            field=models.IntegerField(),
        ),
    ]
